name: selfaugment
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.7
  - torchvision
  - cudatoolkit=9.2
  - pytorch
  - opencv
  - h5py
  - scikit-image
  - pandas
  - jq
  - six
  - pyyaml
  - cython
  - pycurl
  - networkx
  - scikit-learn
  - scipy
  - future
  - protobuf


